# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Solar Control\Solar-Control\UI\SolarControl_Log_page\Log_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(555, 440)
        Form.setMinimumSize(QtCore.QSize(555, 440))
        Form.setMaximumSize(QtCore.QSize(555, 440))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.482198, y1:0.971, x2:0.497, y2:0.023, stop:0.0338983 rgba(46, 46, 46, 255), stop:1 rgba(168, 168, 168, 255));")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 60, 101, 31))
        self.label.setToolTip("")
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%);")
        self.label.setObjectName("label")
        self.Login = QtWidgets.QLineEdit(Form)
        self.Login.setGeometry(QtCore.QRect(180, 140, 201, 41))
        self.Login.setStyleSheet("QLineEdit {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"min-width: 8em;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #a6a6a6\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #b4b4b4, stop: 1 #969696\n"
");\n"
"}\n"
"\n"
"QLineEdit:pressed {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}")
        self.Login.setInputMask("")
        self.Login.setText("")
        self.Login.setPlaceholderText("")
        self.Login.setObjectName("Login")
        self.Logo_cap = QtWidgets.QLabel(Form)
        self.Logo_cap.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.Logo_cap.setMinimumSize(QtCore.QSize(82, 45))
        self.Logo_cap.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/newPrefix/images/backgrounds/PsLYIQ01.svg);")
        self.Logo_cap.setObjectName("Logo_cap")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 370, 171, 31))
        self.label_2.setToolTip("")
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 290, 131, 41))
        self.pushButton.setMinimumSize(QtCore.QSize(131, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(145, 41))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"max-width: 131px;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.Login_2 = QtWidgets.QLineEdit(Form)
        self.Login_2.setGeometry(QtCore.QRect(180, 210, 201, 41))
        self.Login_2.setStyleSheet("QLineEdit {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"min-width: 8em;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #a6a6a6\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #b4b4b4, stop: 1 #969696\n"
");\n"
"}\n"
"\n"
"QLineEdit:pressed {\n"
"border-style: inset;\n"
"background: qradialgradient(\n"
"cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
");\n"
"}")
        self.Login_2.setInputMask("")
        self.Login_2.setText("")
        self.Login_2.setPlaceholderText("")
        self.Login_2.setObjectName("Login_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">SOLAR CONTROL</p></body></html>"))
        self.Login.setWhatsThis(_translate("Form", "Login"))
        self.Logo_cap.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Don`t have an account? <span style=\" color:#882a2a;\">Sign up</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Log in"))
        self.Login_2.setWhatsThis(_translate("Form", "Login"))
import Backgrounds


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
