# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Solar Control\UI\SolarControl_Sign_in_page\Sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(555, 440)
        Form.setMinimumSize(QtCore.QSize(555, 440))
        Form.setMaximumSize(QtCore.QSize(555, 440))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.256, y1:0.272227, x2:1, y2:1, stop:0.511364 rgba(40, 158, 42, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 300, 121, 31))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color:rgb(136, 42, 42);\n"
"font: 8pt \"Comic Sans MS\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Login = QtWidgets.QLineEdit(Form)
        self.Login.setGeometry(QtCore.QRect(180, 90, 201, 41))
        self.Login.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.Login.setInputMask("")
        self.Login.setText("")
        self.Login.setPlaceholderText("")
        self.Login.setObjectName("Login")
        self.Password = QtWidgets.QLineEdit(Form)
        self.Password.setGeometry(QtCore.QRect(180, 220, 201, 41))
        self.Password.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.Password.setInputMask("")
        self.Password.setText("")
        self.Password.setPlaceholderText("")
        self.Password.setObjectName("Password")
        self.E_mail = QtWidgets.QLineEdit(Form)
        self.E_mail.setGeometry(QtCore.QRect(180, 150, 201, 41))
        self.E_mail.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.E_mail.setInputMask("")
        self.E_mail.setText("")
        self.E_mail.setPlaceholderText("")
        self.E_mail.setObjectName("E_mail")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 30, 101, 31))
        self.label.setToolTip("")
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 360, 171, 31))
        self.label_2.setToolTip("")
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Solar Control"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.Login.setWhatsThis(_translate("Form", "Login"))
        self.Password.setWhatsThis(_translate("Form", "Login"))
        self.E_mail.setWhatsThis(_translate("Form", "Login"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">SOLAR CONTROL</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Don`t have an account? <span style=\" color:#882a2a;\">Sign up</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
